---
# tasks file for backend
# В нашей автоматизации список из четырех задач
- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes
- name: Install Java using Ansible
  become: yes
  apt:
    name: "openjdk-16-jdk"
    state: present
- name: Install python3 pip  using Ansible
  become: yes
  apt:
    name: "python3-pip"
    state: present
- name: Install lxml using Ansible
  become: yes
  pip:
    name: "lxml"
    state: present
- name: Добавим сервисного пользователя
  become: true
  user:
    name: "{{ backend_service_user }}"
    create_home: no
    shell: /sbin/nologin
- name: сreate user directory
  become: true
  file:
    path=/home/jarservice
    mode=0755
    owner={{ backend_service_user }}
    group={{ backend_service_user }}
    state=directory
- name: сreate log  directory
  become: true
  file:
    path=/opt/log
    mode=0755
    owner={{ backend_service_user }}
    group={{ backend_service_user }}
    state=directory
- name: сreate reports directory
  become: true
  file:
    path=/opt/log/reports
    mode=0755
    owner={{ backend_service_user }}
    group={{ backend_service_user }}
    state=directory
#непроверенная фича ниже
- name: adding existing user '{{ backend_service_user }}' to group docker
  user:
    name: '{{ backend_service_user }}'
    groups: docker
    append: yes
- name: Используем модуль maven_artifact, он скачает пакет приложения с Nexus
  become: true
  maven_artifact:
    dest: "/home/jarservice/sausage-store.jar"
    repository_url: "{{ backend_nexus_pero }}"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store"
    version: "{{ backend_maven_version }}"
    mode: 0777
    username: "{{ nexus_user }}"
    password: "{{ nexus_pass }}"

- name: Шаблонизация конфига управляет настройками приложения с помощью переменных
  become: true
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service
  notify:
    - Restart systemd service

