---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-010-040/sausage-store/sausage-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_HOST
              value: 158.160.47.201
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: frontend
              containerPort: 80
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: 8080
          #  initialDelaySeconds: 15
          #  periodSeconds: 30
          #  timeoutSeconds: 1
          #  failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
